services:
  flash-card:
    build:
      context: .
      dockerfile: Dockerfile.rust
    env_file:
      - .env 
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db

  scrapy:
    build:
      context: .
      dockerfile: Dockerfile.scrapy
    volumes:
      - ./scrape:/scrape
    depends_on:
      - db


  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: flash_card_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # This creates a named volume for the database

volumes:
  postgres-data:  # Defi