FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /scrape

 #copy scrape folder to scrape
COPY /scrape /scrape


RUN apt-get update && apt-get install -y postgresql-client \
    && pip install --no-cache-dir scrapy psycopg2-binary


# Set the environment variable to prevent Python from writing .pyc files to disk
ENV PYTHONDONTWRITEBYTECODE=1
# Set the environment variable to buffer output
ENV PYTHONUNBUFFERED=1

CMD ["python", "scrape.py"]